//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WifiVideo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WifiVideo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap img_custom {
            get {
                object obj = ResourceManager.GetObject("img_custom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0000_左后 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0000_左后", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0001_右后 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0001_右后", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0002_右前 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0002_右前", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0003_左前 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0003_左前", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0004_后 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0004_后", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0005_右 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0005_右", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0006_左 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0006_左", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0000s_0007_前 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0000s_0007_前", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0001s_0000_图层_7 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0001s_0000_图层-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0001s_0001_图层_6 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0001s_0001_图层-6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0001s_0002_图层_5 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0001s_0002_图层-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0001s_0003_图层_4 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0001s_0003_图层-4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0002s_0007_视频 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0002s_0007_视频", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0002s_0008_设置 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0002s_0008_设置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0002s_0009_照明 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0002s_0009_照明", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0002s_0010_喇叭 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0002s_0010_喇叭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0002s_0011_拍照 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0002s_0011_拍照", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0006_矩形_2 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0006_矩形-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0007_圆角矩形_3 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0007_圆角矩形-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0008_圆角矩形_2 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0008_圆角矩形-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 上位机界面_0009_圆角矩形_1 {
            get {
                object obj = ResourceManager.GetObject("上位机界面_0009_圆角矩形-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 手机app主图 {
            get {
                object obj = ResourceManager.GetObject("手机app主图", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
